### ISSUE TITLE
Arrumar criação de usuario por dicionario

### ISSUE THREAD

**Issue by rreschke** [Maua-Dev/models-devmaua#18]
Ao criar o usuario por dicionario, apenas as informações de contato de indice 0 são instanciadas.
Ex:
```
            email = Email(email=d['contato']['emails'][0]['email'],
                          tipo=d['contato']['emails'][0]['tipo'],
                          prioridade=d['contato']['emails'][0]['prioridade'])

            end = Endereco(logradouro=d['contato']['enderecos'][0]['logradouro'],
                           numero=d['contato']['enderecos'][0]['numero'],
                           cep=d['contato']['enderecos'][0]['cep'],
                           tipo=d['contato']['enderecos'][0]['tipo'],
                           complemento=d['contato']['enderecos'][0]['complemento'])
            tel = Telefone(tipo=d['contato']['telefones'][0]['tipo'],
                           numero=d['contato']['telefones'][0]['numero'],
                           ddd=d['contato']['telefones'][0]['ddd'],
                           prioridade=d['contato']['telefones'][0]['prioridade'])
```
Porém, é possível passar mais de 1 telefone (ex).
Arrumar a criação de usuario por dict para que todas as informações de contato sejam cadastradas efetivamente

**Comment by Brvilardi** [comment]
@Renan-Reschke , na hora de cadastrar o usuário vai passar mais de 1 telefone? Isso não entraria em alteração do cadastro?

**Comment by rreschke** [comment]
Esse método pode ser utilizado para instanciar um usuario a qualquer momento, não apenas na hora do cadastro.
Por exemplo, eu ao fazer o teste unitário de deletar email preciso instanciar um com ao menos 2 emails.
A alteração que fiz nao quebra a sua implementação e facilita muito a minha vida haha, fica tranquilo.

**Comment by Brvilardi** [comment]
Show!!! Era mais pra entender a usabilidade. Faz total sentido
