### ISSUE TITLE
Deletar branches automaticamente após PR

### ISSUE THREAD

**Issue by VitorMartin** [Maua-Dev/models-devmaua#5]

**Comment by Brvilardi** [comment]
Segui esse passo a passo aqui, mudando uma config no repositório, pls, @VitorMartin  , me confirma se quando alguem fizer o merge ele apaga a branch - se der certo eu já faço nos outros repos

https://docs.github.com/en/github/administering-a-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches

**Comment by VitorMartin** [comment]
> Segui esse passo a passo aqui, mudando uma config no repositório, pls, @VitorMartin , me confirma se quando alguem fizer o merge ele apaga a branch - se der certo eu já faço nos outros repos
> 
> https://docs.github.com/en/github/administering-a-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches

Acho que foi, ne? Acabei de aceitar Seu PR #8 e a branch dele sumiu.
